version: "3.9"

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data:

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=Portfolio FastAPI
      - CONTACT_EMAIL=your.email@example.com
    networks:
      - monitoring
    restart: unless-stopped

  locust:
    image: locustio/locust:2.19.0
    container_name: locust
    entrypoint: ["sh", "/mnt/locust/docker-entrypoint.sh"]
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: >
      -f /mnt/locust/loadshape_stability.py
      --host=http://web:8000
      --web-host=0.0.0.0
    depends_on:
      - web
    networks:
      - monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - web
      - locust
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: unless-stopped